version: '3.7'
services:
  app:
    container_name: dev_app
    restart: on-failure
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - gulp
  db:
    container_name: dev_db
    image: postgres:14-alpine
    restart: on-failure
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  gulp:
    container_name: dev_gulp
    build:
      context: ./
      dockerfile: ./docker/gulp/Dockerfile
    command: gulp watch
    volumes:
      - .:/app

volumes:
  postgres_data: